services:
  postgres:
    image: postgres
    container_name: db-container
    environment:
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: politician-db
    volumes:
      - ./database/scripts/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
